# 组件配置
# enabled_components: 启用的组件列表（注释掉的不加载）
enabled_components:
  - app.components.calculator.Calculator
  - app.components.greeter.Greeter
  - app.components.jsontest.JsonTest
  - app.components.jstest.JsTest

# 窗口配置
window:
  width: 1200
  height: 800
  # 是否移除原生标题栏（true: 无标题栏, false: 显示原生标题栏）
  remove_titlebar: true
